import React from 'react';
import { Typography, Box, Button } from '@mui/material';
import DataTable from '../components/Common/DataTable';

const Reports = () => {
  const columns = [
    { id: 'id', label: 'ID' },
    { id: 'reportName', label: 'Report Name' },
    { id: 'category', label: 'Category' },
    { id: 'generatedDate', label: 'Generated Date' },
    { id: 'generatedBy', label: 'Generated By' },
    { id: 'format', label: 'Format' },
    { id: 'status', label: 'Status' },
  ];

  const rows = [];

  return (
    <Box>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 3 }}>
        <Typography variant="h5">Reports Management</Typography>
        <Button variant="contained" color="primary">
          Generate New Report
        </Button>
      </Box>
      <DataTable
        columns={columns}
        rows={rows}
        page={0}
        rowsPerPage={10}
        onPageChange={() => {}}
        onRowsPerPageChange={() => {}}
        onEdit={() => {}}
        onDelete={() => {}}
        totalRows={0}
      />
    </Box>
  );
};

export default Reports;